# Generated by Django 5.0.6 on 2026-07-06 21:46

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, max_length=8)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nickname', models.CharField(db_index=True, max_length=64)),
                ('real_name', models.CharField(blank=True, max_length=128)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('residency', models.CharField(db_index=True, max_length=8)),
                ('continent', models.CharField(blank=True, max_length=16)),
                ('primary_role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], db_index=True, max_length=16)),
                ('secondary_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('attributes', models.JSONField(default=dict)),
                ('career_stats', models.JSONField(default=dict)),
                ('worlds_count', models.IntegerField(db_index=True, default=0)),
                ('worlds_titles_count', models.IntegerField(db_index=True, default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nickname'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='players_pla_attribu_6fbfb3_gin'), models.Index(fields=['primary_role', 'is_active'], name='players_pla_primary_2d7d49_idx'), models.Index(fields=['nickname'], name='players_pla_nicknam_6ee510_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], max_length=16)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
            options={
                'verbose_name_plural': 'Player team history',
            },
        ),
        migrations.CreateModel(
            name='PlayerCoachHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team')),
            ],
            options={
                'verbose_name_plural': 'Player coach history',
                'unique_together': {('player', 'coach', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TournamentAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_slug', models.CharField(db_index=True, max_length=64)),
                ('year', models.IntegerField(db_index=True)),
                ('role', models.CharField(blank=True, choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], max_length=16)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_appearances', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.team')),
            ],
            options={
                'unique_together': {('player', 'tournament_slug')},
            },
        ),
    ]
