# Generated by Django 5.0.6 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='continent',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='player',
            name='country_code',
            field=models.CharField(blank=True, default='KR', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_role',
            field=models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], db_index=True, default='mid', max_length=16),
        ),
        migrations.AlterField(
            model_name='player',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='residency',
            field=models.CharField(blank=True, db_index=True, default='LCK', max_length=8),
        ),
    ]
