# Generated by Django 5.0.6 on 2026-07-06 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailies', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('points_common', models.IntegerField(default=10)),
                ('points_rare', models.IntegerField(default=25)),
                ('points_epic', models.IntegerField(default=60)),
                ('points_legendary', models.IntegerField(default=120)),
                ('diamond_bonus', models.IntegerField(default=50)),
                ('threshold_rare', models.FloatField(default=20.0)),
                ('threshold_epic', models.FloatField(default=10.0)),
                ('threshold_legendary', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('pick_percent', models.FloatField(default=0)),
                ('rarity_tier', models.CharField(max_length=16)),
                ('is_correct', models.BooleanField(default=True)),
                ('daily_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailies.dailyslot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'unique_together': {('daily_slot', 'player')},
            },
        ),
    ]
