# Generated by Django 5.0.6 on 2026-07-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('scored', 'Scored')], default='draft', max_length=16)),
                ('locale_seed', models.CharField(blank=True, max_length=64)),
                ('reveal_mode', models.CharField(choices=[('after_close', 'After Close'), ('instant', 'Instant')], default='after_close', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dailies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], max_length=16)),
                ('label_pl', models.CharField(blank=True, max_length=128)),
                ('label_en', models.CharField(blank=True, max_length=128)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='dailies.daily')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('daily', 'position'), ('daily', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DailySlotCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('role', 'Role'), ('region', 'Region'), ('residency', 'Residency'), ('country', 'Country'), ('continent', 'Continent'), ('team', 'Team'), ('league', 'League'), ('worlds_appearance', 'Worlds appearance'), ('worlds_champion', 'Worlds champion'), ('msi_appearance', 'MSI appearance'), ('coach', 'Coach'), ('champion_played', 'Champion played'), ('birth_year_range', 'Birth year range'), ('active', 'Active'), ('worlds_titles_min', 'Worlds titles min')], max_length=32)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('in', 'In'), ('gte', '>='), ('lte', '<='), ('any', 'Any')], default='eq', max_length=8)),
                ('value', models.JSONField()),
                ('label_pl', models.CharField(max_length=256)),
                ('label_en', models.CharField(max_length=256)),
                ('order', models.IntegerField(default=0)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dailies.dailyslot')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
