# Generated by Django 5.0.6 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='reveal_mode',
            field=models.CharField(choices=[('after_close', 'After Close'), ('instant', 'Instant')], default='instant', max_length=16),
        ),
    ]
