# Generated by Django 5.0.6 on 2026-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0002_alter_daily_reveal_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='reveal_mode',
            field=models.CharField(choices=[('instant', 'Instant')], default='instant', max_length=16),
        ),
    ]
