# Generated by Django 5.0.6 on 2026-07-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailies', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('is_scored', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dailies.daily')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('rarity_tier', models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=16, null=True)),
                ('rarity_percent', models.FloatField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('is_diamond_pick', models.BooleanField(default=False)),
                ('diamond_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('daily_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dailies.dailyslot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('daily', 'user'), name='uniq_daily_user'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_token__isnull', False)), fields=('daily', 'guest_token'), name='uniq_daily_guest'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_diamond_pick', True)), fields=('daily_slot', 'player'), name='uniq_diamond_per_slot_player'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionanswer',
            unique_together={('submission', 'daily_slot')},
        ),
    ]
